source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PinAutoLayout_Example' do
  pod "PinAutoLayout", :path => "../"
end

target 'PinAutoLayout_Tests' do
  pod "PinAutoLayout", :path => "../"

  
end
