source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
use_frameworks!

target 'PinAutoLayout_Example', :exclusive => true do
  pod "PinAutoLayout", :path => "../"
  pod 'RandomColorSwift'
end

target 'PinAutoLayout_Tests', :exclusive => true do
  pod "PinAutoLayout", :path => "../"
  pod 'RandomColorSwift'
end
